version: '3.3'

services:
  tg-edu-system:
    build: .
    container_name: tg-edu-system
    ports:
      - "20001:5000"
    environment:
      # 管理员账户配置（可以修改这些值）
      - ADMIN_USERNAME=root
      - ADMIN_PASSWORD=Root@123
      # 应用安全密钥（建议在生产环境中修改）
      - SECRET_KEY=root
    restart: unless-stopped
    volumes:
      # 持久化数据库文件到本地目录
      - ./data:/app/data
      # 持久化上传文件到本地目录
      - ./uploads:/app/uploads
      # 持久化附件文件到本地目录
      - ./appendix:/app/appendix

# 注意：使用本地目录挂载，不需要 Docker volumes